---
- name: Deploy Jenkins, Trivy, Nexus, and SonarQube on AWS
  hosts: all
  become: yes

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - wget
          - gnupg
          - lsb-release
          - apt-transport-https
          - docker.io
          - python3-docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy install_jenkins.sh script to remote host
      copy:
        src: ./install_jenkins.sh
        dest: /tmp/install_jenkins.sh
        mode: '0755'

    - name: Execute install_jenkins.sh
      command: /tmp/install_jenkins.sh
      register: jenkins_install
      ignore_errors: yes

    - name: Print Jenkins installation output
      debug:
        var: jenkins_install.stdout_lines

    - name: Start and enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Pull Nexus Docker image
      docker_image:
        name: sonatype/nexus3
        tag: latest

    - name: Run Nexus container
      docker_container:
        name: nexus
        image: sonatype/nexus3:latest
        ports:
          - "8081:8081"
        restart_policy: unless-stopped

    - name: Pull SonarQube Docker image
      docker_image:
        name: sonarqube
        tag: lts-community

    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        ports:
          - "9000:9000"
        environment:
          SONAR_JDBC_URL: jdbc:h2:tcp://sonarqube-db:9092/sonar
          SONAR_JDBC_USERNAME: sonar
          SONAR_JDBC_PASSWORD: sonar
        restart_policy: unless-stopped

    - name: Copy install_trivy.sh script to remote host
      copy:
        src: ./install_trivy.sh
        dest: /tmp/install_trivy.sh
        mode: '0755'

    - name: Execute install_trivy.sh
      command: /tmp/install_trivy.sh
      register: trivy_install
      ignore_errors: yes

    - name: Print Trivy installation output
      debug:
        var: trivy_install.stdout_lines
