---
- name: Deploy Docker Compose application
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker Compose is installed
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Copy Docker Compose file to remote host
      copy:
        src: ./docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yml

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
