---
- name: Set up Kubernetes cluster
  hosts: kube_cluster
  become: yes
  roles:
    - common
    - kube

- name: Initialize Kubernetes master
  hosts: masters
  become: yes
  tasks:
    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init
      changed_when: "'kubeadm join' in kubeadm_init.stdout"

    - name: Copy kubeconfig for master
      command: mkdir -p $HOME/.kube
      become_user: <user>
      when: kubeadm_init.changed

    - name: Copy kubeconfig for master
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
      become_user: <user>
      when: kubeadm_init.changed

    - name: Change ownership of kubeconfig
      file:
        path: $HOME/.kube/config
        owner: <user>
        group: <user>
      become_user: <user>
      when: kubeadm_init.changed

    - name: Deploy Calico networking
      kubectl:
        kubeconfig: $HOME/.kube/config
        src: https://docs.projectcalico.org/v3.20/manifests/calico.yaml
        state: present

    - name: Deploy NGINX Ingress Controller
      kubectl:
        kubeconfig: $HOME/.kube/config
        src: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.49.0/deploy/static/provider/baremetal/deploy.yaml
        state: present

